/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is kept in sync here because route files are committed directly to the repository.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/_painel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PainelCaixaRouteImport } from './routes/_painel/caixa'
import { Route as PainelClientesRouteImport } from './routes/_painel/clientes'
import { Route as PainelComandasRouteImport } from './routes/_painel/comandas'
import { Route as PainelConfiguracoesRouteImport } from './routes/_painel/configuracoes'
import { Route as PainelDashboardRouteImport } from './routes/_painel/dashboard'
import { Route as PainelEstoqueRouteImport } from './routes/_painel/estoque'
import { Route as PainelFiadoRouteImport } from './routes/_painel/fiado'
import { Route as PainelPdvRouteImport } from './routes/_painel/pdv'
import { Route as PainelProdutosRouteImport } from './routes/_painel/produtos'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const PainelRoute = PainelRouteImport.update({ id: '/_painel', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const PainelCaixaRoute = PainelCaixaRouteImport.update({ id: '/caixa', path: '/caixa', getParentRoute: () => PainelRoute } as any)
const PainelClientesRoute = PainelClientesRouteImport.update({ id: '/clientes', path: '/clientes', getParentRoute: () => PainelRoute } as any)
const PainelComandasRoute = PainelComandasRouteImport.update({ id: '/comandas', path: '/comandas', getParentRoute: () => PainelRoute } as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({ id: '/configuracoes', path: '/configuracoes', getParentRoute: () => PainelRoute } as any)
const PainelDashboardRoute = PainelDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => PainelRoute } as any)
const PainelEstoqueRoute = PainelEstoqueRouteImport.update({ id: '/estoque', path: '/estoque', getParentRoute: () => PainelRoute } as any)
const PainelFiadoRoute = PainelFiadoRouteImport.update({ id: '/fiado', path: '/fiado', getParentRoute: () => PainelRoute } as any)
const PainelPdvRoute = PainelPdvRouteImport.update({ id: '/pdv', path: '/pdv', getParentRoute: () => PainelRoute } as any)
const PainelProdutosRoute = PainelProdutosRouteImport.update({ id: '/produtos', path: '/produtos', getParentRoute: () => PainelRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof PainelCaixaRoute
  '/clientes': typeof PainelClientesRoute
  '/comandas': typeof PainelComandasRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/estoque': typeof PainelEstoqueRoute
  '/fiado': typeof PainelFiadoRoute
  '/pdv': typeof PainelPdvRoute
  '/produtos': typeof PainelProdutosRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_painel': typeof PainelRouteWithChildren
  '/auth': typeof AuthRoute
  '/_painel/caixa': typeof PainelCaixaRoute
  '/_painel/clientes': typeof PainelClientesRoute
  '/_painel/comandas': typeof PainelComandasRoute
  '/_painel/configuracoes': typeof PainelConfiguracoesRoute
  '/_painel/dashboard': typeof PainelDashboardRoute
  '/_painel/estoque': typeof PainelEstoqueRoute
  '/_painel/fiado': typeof PainelFiadoRoute
  '/_painel/pdv': typeof PainelPdvRoute
  '/_painel/produtos': typeof PainelProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  fileRoutesById: FileRoutesById
  id: keyof FileRoutesById
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_painel': { id: '/_painel'; path: ''; fullPath: '/'; preLoaderRoute: typeof PainelRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_painel/caixa': { id: '/_painel/caixa'; path: '/caixa'; fullPath: '/caixa'; preLoaderRoute: typeof PainelCaixaRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/clientes': { id: '/_painel/clientes'; path: '/clientes'; fullPath: '/clientes'; preLoaderRoute: typeof PainelClientesRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/comandas': { id: '/_painel/comandas'; path: '/comandas'; fullPath: '/comandas'; preLoaderRoute: typeof PainelComandasRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/configuracoes': { id: '/_painel/configuracoes'; path: '/configuracoes'; fullPath: '/configuracoes'; preLoaderRoute: typeof PainelConfiguracoesRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/dashboard': { id: '/_painel/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof PainelDashboardRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/estoque': { id: '/_painel/estoque'; path: '/estoque'; fullPath: '/estoque'; preLoaderRoute: typeof PainelEstoqueRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/fiado': { id: '/_painel/fiado'; path: '/fiado'; fullPath: '/fiado'; preLoaderRoute: typeof PainelFiadoRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/pdv': { id: '/_painel/pdv'; path: '/pdv'; fullPath: '/pdv'; preLoaderRoute: typeof PainelPdvRouteImport; parentRoute: typeof PainelRoute }
    '/_painel/produtos': { id: '/_painel/produtos'; path: '/produtos'; fullPath: '/produtos'; preLoaderRoute: typeof PainelProdutosRouteImport; parentRoute: typeof PainelRoute }
  }
}

interface PainelRouteChildren {
  PainelCaixaRoute: typeof PainelCaixaRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelComandasRoute: typeof PainelComandasRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelDashboardRoute: typeof PainelDashboardRoute
  PainelEstoqueRoute: typeof PainelEstoqueRoute
  PainelFiadoRoute: typeof PainelFiadoRoute
  PainelPdvRoute: typeof PainelPdvRoute
  PainelProdutosRoute: typeof PainelProdutosRoute
}
const PainelRouteChildren: PainelRouteChildren = {
  PainelCaixaRoute,
  PainelClientesRoute,
  PainelComandasRoute,
  PainelConfiguracoesRoute,
  PainelDashboardRoute,
  PainelEstoqueRoute,
  PainelFiadoRoute,
  PainelPdvRoute,
  PainelProdutosRoute,
}
const PainelRouteWithChildren = PainelRoute._addFileChildren(PainelRouteChildren)
export interface RootRouteChildren { IndexRoute: typeof IndexRoute; PainelRoute: typeof PainelRouteWithChildren; AuthRoute: typeof AuthRoute }
const rootRouteChildren: RootRouteChildren = { IndexRoute, PainelRoute: PainelRouteWithChildren, AuthRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
