/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/_painel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PainelCaixaRouteImport } from './routes/_painel/caixa'
import { Route as PainelComandasRouteImport } from './routes/_painel/comandas'
import { Route as PainelConfiguracoesRouteImport } from './routes/_painel/configuracoes'
import { Route as PainelDashboardRouteImport } from './routes/_painel/dashboard'
import { Route as PainelEstoqueRouteImport } from './routes/_painel/estoque'
import { Route as PainelPdvRouteImport } from './routes/_painel/pdv'
import { Route as PainelProdutosRouteImport } from './routes/_painel/produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/_painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelCaixaRoute = PainelCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => PainelRoute,
} as any)
const PainelComandasRoute = PainelComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDashboardRoute = PainelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstoqueRoute = PainelEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPdvRoute = PainelPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => PainelRoute,
} as any)
const PainelProdutosRoute = PainelProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof PainelCaixaRoute
  '/comandas': typeof PainelComandasRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/estoque': typeof PainelEstoqueRoute
  '/pdv': typeof PainelPdvRoute
  '/produtos': typeof PainelProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof PainelCaixaRoute
  '/comandas': typeof PainelComandasRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/estoque': typeof PainelEstoqueRoute
  '/pdv': typeof PainelPdvRoute
  '/produtos': typeof PainelProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_painel': typeof PainelRouteWithChildren
  '/auth': typeof AuthRoute
  '/_painel/caixa': typeof PainelCaixaRoute
  '/_painel/comandas': typeof PainelComandasRoute
  '/_painel/configuracoes': typeof PainelConfiguracoesRoute
  '/_painel/dashboard': typeof PainelDashboardRoute
  '/_painel/estoque': typeof PainelEstoqueRoute
  '/_painel/pdv': typeof PainelPdvRoute
  '/_painel/produtos': typeof PainelProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caixa'
    | '/comandas'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/pdv'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/caixa'
    | '/comandas'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/pdv'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/_painel'
    | '/auth'
    | '/_painel/caixa'
    | '/_painel/comandas'
    | '/_painel/configuracoes'
    | '/_painel/dashboard'
    | '/_painel/estoque'
    | '/_painel/pdv'
    | '/_painel/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel': {
      id: '/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel/caixa': {
      id: '/_painel/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof PainelCaixaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/comandas': {
      id: '/_painel/comandas'
      path: '/comandas'
      fullPath: '/comandas'
      preLoaderRoute: typeof PainelComandasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/configuracoes': {
      id: '/_painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/dashboard': {
      id: '/_painel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PainelDashboardRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/estoque': {
      id: '/_painel/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof PainelEstoqueRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/pdv': {
      id: '/_painel/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PainelPdvRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/produtos': {
      id: '/_painel/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof PainelProdutosRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelCaixaRoute: typeof PainelCaixaRoute
  PainelComandasRoute: typeof PainelComandasRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelDashboardRoute: typeof PainelDashboardRoute
  PainelEstoqueRoute: typeof PainelEstoqueRoute
  PainelPdvRoute: typeof PainelPdvRoute
  PainelProdutosRoute: typeof PainelProdutosRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelCaixaRoute: PainelCaixaRoute,
  PainelComandasRoute: PainelComandasRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelDashboardRoute: PainelDashboardRoute,
  PainelEstoqueRoute: PainelEstoqueRoute,
  PainelPdvRoute: PainelPdvRoute,
  PainelProdutosRoute: PainelProdutosRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
